version: '3'
services:
# starts container defined by the Dockerfile with context ; exposing 8080 to 80 internally  
  nginx:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
