version: '3.4'

services:
  liferay:
    image: liferay/dxp:7.1.10.1
    ports:
      - "80:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s     
