version: '3.4'

services:
  liferay:
    image: customdxp
    build:
      context: .
      dockerfile: liferay.Dockerfile
    ports:
      - "80:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on: 
      - db   
  db:
    image: postgres
    restart: always
#    environment:
#      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
      
  elastic-node:
    image: elasticsearch:6.7.2
    environment: 
      discovery.type: single-node


